name: "Embarrassing"
on:
    workflow_dispatch:
jobs:
    build-frontend:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: frontend
        steps:
            - uses: actions/checkout@v4
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v2

            - run: bun install
            - run: bun run build
            - uses: actions/upload-artifact@v4
              with:
                  name: frontend
                  path: frontend/dist
