name: "Build and release static binary"
on:
  push:
    tags:
      - "v*"
jobs:
  static-build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
        with:
          name: foldu
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix build .#
      - uses: softprops/action-gh-release@v2
        with:
          files: result/bin/aiswitch
